name: jlogger
description: Simple Flutter console logger with traceable log. Improves readability of logs.
version: 0.0.5
homepage: https://github.com/jhool/flutter-logger

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
